version: 2.1

orbs: 
  python: circleci/python@2.0.3
  rust: circleci/rust@1.6.0

jobs:
  # Build
  install_python_dependencies:
    docker:
      - image: cimg/python:3.10.4

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - python/install-packages:
          venv-path: venv
      - run:
          name: Set up virtualenv
          command: > 
            python -m venv venv && 
            source ./venv/bin/activate

  install_rust_dependencies:
    docker:
      - image: cimg/rust:1.61.0

    steps:
      - checkout
      - rust/install

  pyo3_initialize:
    docker:
      - image: cimg/python:3.10.4

    steps:
      - checkout
      - run:
          name: Generate new package source for PyO3
          command: maturin init

  pyo3_develop:
    docker:
      - image: cimg/python:3.10.4

    steps:
      - checkout
      - run:
          name: Build package and install Rust bindings into virtualenv
          command: maturin develop

  # Test
  test_pyo3:
    docker:
      - image: cimg/python:3.10.4

    working_directory: ~/project/src/

    steps:
      - checkout
      - run:
          name: Run sample code using imported library compiled from Rust
          command: python main.py

  # Development
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: large

    steps:
      - checkout
    #  takes too long with no output
      # - run:
      #     name: Update and upgrade Linux packages 
      #     command: >
      #       sudo apt-get update && 
      #       sudo apt-get upgrade -y
      - run:
          name: Install Python 3.10
          command: >
            sudo apt install software-properties-common -y &&
            sudo add-apt-repository ppa:deadsnakes/ppa -y &&
            sudo apt-get install python3.10 -y
      - run:
          name: Install pip package manager for Python 3.10
          command: sudo apt-get install python3-distutils -y
      # - python/install-packages:
      #     venv-path: venv
      - run:
          name: Create virtualenv
          command: > 
            python3.10 -m venv venv && 
            source ./venv/bin/activate
      - run:
          name: Install required packages for Python
          command: ./venv/bin/pip install -r requirements.txt
      - rust/install
      - run:
          name: Compile Rust bindings to Python
          command: >
            ./venv/bin/maturin init && 
            ./venv/bin/maturin develop
      - run:
          name: Run sample code using imported library compiled from Rust
          command: python ~/project/src/main.py

workflows:
  dev:
    jobs:
      # - install_python_dependencies
      # - install_rust_dependencies
      # - pyo3_develop:
      #     requires:
      #       - install_python_dependencies
      #       - install_rust_dependencies
      # - test_pyo3:
      #     requires:
      #       - pyo3_develop

      - build